FROM centos 
SHELL ["/bin/bash", "-c"]
WORKDIR '/application'
COPY ./package.json .
RUN yum update -y
RUN yum install -y gcc-c++ make
RUN curl -sL https://rpm.nodesource.com/setup_14.x | bash -
RUN yum install nodejs -y
RUN npm install
COPY . .
CMD ["npm", "run", "start"]
