version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /myapplication
      - .:/application
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev  
    volumes:
      - /myapplication
      - .:/application
    command: ["npm", "run", "test"]  
    restart: always
